= Efficient Graph Algorithms for Neo4j (pre-Alpha / WIP)

image:https://travis-ci.org/neo4j-contrib/neo4j-graph-algorithms.svg?branch=3.1["Build Status", link="https://travis-ci.org/neo4j-contrib/neo4j-graph-algorithms"]

This project aims to develop efficient, well tested graph algorithm implementations for Neo4j 3.1.

You can find the documentation (WIP) here http://neo4j-contrib.github.io/neo4j-graph-algorithms

Releases are available here: https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases

The goal is to provide parallel versions of common graph algorithms for Neo4j exposed as Cypher user defined procedures:

* Page Rank
* Betweenness Centrality
* Closeness Centrality
* Clustering: Louvain
* Clustering: Label Propagation
* Minimum Weight Spanning Tree
* All Pairs- and Single Source - Shortest Path
* (Weakly) Connected Components
* Strongly Connected Components

These procedures work on a subgraph optionally filtered by label and relationship-type. Future versions will also provide filtering and projection using Cypher queries.

We'd love your feedback, so please try out these algorithms and let us know how well they work for your use-case. Also please note things that you miss from installation instructions, readme, etc. 

Please raise https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues[GitHub issues] for anything you encounter or join the http://neo4j.com/developer/slack[neo4j-users Slack group] and ask in the `#neo4j-graph-algorithm` channel.

== Installation

Just copy the `graph-algorithms-algo-*.jar` from the https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases[release] into your `$NEO4J_HOME/plugins` directory and restart Neo4j.

Then running `call dbms.procedures();` should also list the algorithm procedures.

----
call dbms.procedures() yield name, description 
where name starts with "algo." and not name starts with "algo.algo."
return name, description
order by name
----

Details on how to call them can be found in the http://neo4j-contrib.github.io/neo4j-graph-algorithms[project's documentation]

== Building

Currently aiming at Neo4j 3.1

----
mvn clean install
cp algo/target/graph-algorithms-3.1.0-SNAPSHOT.jar $NEO4J_HOME/plugins/
$NEO4J_HOME/bin/neo4j restart
----

