[[algorithms]]
= Algorithms

ifdef::env-docs[]
[abstract]
--
This chapter provides explanations and examples for each of the algorithms in the Neo4j Graph Algorithms library.
--
endif::env-docs[]

Graph algorithms are used to compute metrics for graphs, nodes, or relationships.

They can provide insights on relevant entities in the graph (centralities, ranking), or inherent structures like communities (community-detection, graph-partitioning, clustering).

Many graph algorithms are iterative approaches that frequently traverse the graph for the computation using random walks, breadth-first or depth-first searches, or pattern matching.

Due to the exponential growth of possible paths with increasing distance, many of the approaches also have high algorithmic complexity.

Fortunately, optimized algorithms exist that utilize certain structures of the graph, memoize already explored parts, and parallelize operations.
Whenever possible, we've applied these optimizations.

// todo introduction to graph algorithms, also say something about pregel & parallelization
// todo sensible ordering


include::pagerank.adoc[leveloffset=2]

include::articlerank.adoc[leveloffset=2]

include::betweenness-centrality.adoc[leveloffset=2]

include::closeness-centrality.adoc[leveloffset=2]

include::harmonic-centrality.adoc[leveloffset=2]

include::minimum-weight-spanning-tree.adoc[leveloffset=2]

include::shortest-path.adoc[leveloffset=2]

include::single-shortest-path.adoc[leveloffset=2]

include::astar.adoc[leveloffset=2]

include::yens-k-shortest-paths.adoc[leveloffset=2]

include::all-pairs-shortest-path.adoc[leveloffset=2]

include::triangleCount.adoc[leveloffset=2]

include::label-propagation.adoc[leveloffset=2]

include::louvain.adoc[leveloffset=2]

include::connected-components.adoc[leveloffset=2]

include::strongly-connected-components.adoc[leveloffset=2]

include::random-walk.adoc[leveloffset=2]
