= Algorithm Procedures API Discussion

We would like to discuss design of the procedure API for algorithms. 
There are several concerns:

== Naming 

* simple procedure names, 
* consistent spelling and casing
* discriminate between write-back and result-streaming procedure with `.stream` suffix
* default algorithm name should be the best implementation
* other implementations can provided via suffixes

== Input Graph Data 

* load via label/rel-type selection and optional weight/values
* load via cypher statements
* the requirements for node-id's, degrees, weights, relationships etc. comes from the algorithm

== Algorithm parameters

* start-nodes
* iterations, dampening
* concurrency, batch-sizes
* thresholds
* write-back, write-back properties

== Id-Mapping

* original node-ids from the graph are mapped to a consecutive id-range to be used for the algorithm
* this allows simple array offsets to be used within the computation
* this also allows mapping of larger id-ranges to the computational range of the algorithm ()

== Result parameters

* output statistics: number of nodes and rels touched
* time for loading, processing, and writing
* property written to
* errors
* data summary, e.g. 
** min,max,avg of a centrality, rank or weight measure 
** output of all clusters, their sizes and perhaps the root node

* alternatively streaming back node-ids and the computed value (score)

== Constraints:

1. there is no overloading so we need differing names
2. there are default procedure parameters so we need to require only what's really required to run
3. we should use sensible defaults
4. result values/columns have to be pre-declared, there is no inheritance or generics

== Suggestions: 

=== Naming: 2 variants per algorithm

1. returning summary statistics after run: `algo.pageRank(...)` 
2. returning a stream of data: `algo.pageRank.stream(...)`
default should be the one with statistics, as the scroll back from a medium size / large grap will kill the client

=== Parameters

1. node-selector or null - label(s) or cypher statement: ":Person|User" / "MATCH (u:User) RETURN id(u) as id, u.name as value"
2. relationship-selector or null - rel-type(s) or cypher statement ":KNOWS|FRIEND" / "MATCH (u1:User)-[r:KNOWS|FRIEND]-(u2:User) RETURN id(u1) as source, id(u2) as target, r.strength as weight"
3. configuration map with optinal parameters but sensible defaults: {iterations: 5, write:true, nodeValue:"value",nodeWeight:"weight",relationshipWeight:"weight", threshold: 0.85}

We could have the configuration map come from a function (per algorithm?) that handles validation and returns a correct map object for that algorithm? Or just pass the plain map?

=== Example: 

[source,cypher]
----
call algo.pageRank("Person","KNOWS",{iterations:10, write:true, [property:"pagerank"]});

call algo.unionFind.stream('
MATCH (p:Person) RETURN id(p) as id
','
MATCH (p1:Person)-[:KNOWS]-(p2:Person) RETURN id(p1) as source, id(p2) as target
', {}) YIELD nodeId, clusterId
----