= API documentation

== Development notes

NOTE: When implementing a procedure that yields any results (is not `void`) and writes back to the database, make sure to consume the `Result` after running the algorithm call!

Algorithms are executed within a transaction, that is opened and closed by Cypher.
The transaction is only marked successful if the results are consumed.
Closing the Result directly will fail and rollback any open transactions and thus will revert all write-back operations.
// StandardInternalExecutionResult#successful is only set to true _after_ the result has been consumed


== The model

The basic idea behind our model is to have a fast cache for the topology of the graph containing only relevant nodes, relations and in addition the weights.
It implicitly maps (long) node-id's to an internal integer-id (32bit) in ascending order which ensures that no id gets bigger
then the maximum node count.
This approach allows us to use primitive arrays as container for example.

=== Graph interface

The `Graph` interface specifies methods for iterating over all nodes of the graph as well as iterating over relationships of a given node in the form of `forEach...(..)`-methods.
The Graph knows the `nodeCount` and `degree` of each node and can map nodeId to internalId and vice versa.
// An Iterator is implemented for (single-)weighted and unweighted edges.


[options=header,cols="m,"]
|===
| Method | Description
| Collection<PrimitiveIntIterable> batchIterables(int batchSize);
| return a collection of iterables over every node, partitioned by the given batch size.

| boolean contains(long nodeId);
| Returns true iff the nodeId is mapped, otherwise false

| int degree(int nodeId, Direction direction);
| degree of the node in that direction

| void forEachNode(IntPredicate consumer);
| Iterate over each nodeId

| void forEachRelationship(int nodeId, Direction direction, RelationshipConsumer consumer);
| Iterate over all relationships of a node

| void forEachRelationship(int nodeId, Direction direction, WeightedRelationshipConsumer consumer);
| Iterate over all weighted relationships of a node

| int nodeCount();
| count of nodes
| PrimitiveIntIterator nodeIterator();
| iterate over all nodes

| int toMappedNodeId(long nodeId);
| Map neo4j nodeId to internal nodeId

| long toOriginalNodeId(int nodeId);
| Map internal nodeId back to original nodeId

|===

[ditaa]
----

                                  +--------------+
                                  |    Graph     |
                                  +--------------+
                                  | - degree( )  |
                                  | - forEach( ) |
                                  | - relation( )|
                                  | - idMap( )   |
                                  +--------------+
                                    ^    ^     ^
                        implements  |    |     | implements
                      +-------------+    |     +----------+
                      |                  |                |
                      |                  |implements      |
                 +----+-------+    +-----+------+     +---+-------+
                 | HeavyGraph |    | LightGraph |     | GraphView |
                 +------------+    +------------+     +-----------+

----

[NOTE]
Currently we have 3 different implementations aiming for different goals like performance, memory consumption and accuracy.

`HeavyGraph`

This implementations utilizes an int-matrix for storing connections between vertices.
It has a higher memory consumption but performs basic calculations on the graph around 3 times faster then the memory efficient implementation.
Furthermore the number of edges per node is limited only to the maximum array size (2bn) of the JVM.
Relationships can be added in arbitrary order.

`LightGraph`

This implementation takes 3 times less heap due to a more intelligent memory layout.
The drawback is slightly higher evaluation time and that the data cannot be loaded in parallel (yet).

`GraphView`

The View is just a simple wrapper around the Neo4j Kernel API.
It has been implemented for tests and benchmarks baselines.

== Import

A fair amount of the work is to fetch the relevant data from Neo4j and import it into our model.
Fortunately we can use a multithreading approach to load the graph.
This is part of the current implementation.

The abstract `GraphFactory` specifies a constructor and the `build` method.
It is responsible for creating the Graph using the Neo4j Kernel API.

[ditaa]
----

             +------------------+         builds        +--------------+
             |   GraphFactory   | - - - - - - - - - - > |    Graph     |
             +------+---+-------+                       +---+-----+----+
                    ^   ^                                   ^     ^
                    |   |                                   |     |
                    |   |                                   |     |
                    |   |                                   |     |
                +---+   +--------+                   +------+     +--+
                |                |                   |               |
        +-------+------+  +------+-------+    +------+-----+  +------+-----+
        | HeavyFactory |  | LightFactory |    | HeavyGraph |  | LightGraph |
        +--------------+  +--------------+    +------------+  +------------+

----

Loading the Graph is done by using the GraphLoader which implements a simple fluent Builder Pattern.

[source,java]
----
final Graph graph = new GraphLoader( graphDatabaseAPI )
        .setLabel( .. )
        .setRelation( .. )
        .setProperty( .. )
        .setThreadPool( .. )
        .load( FactoryImpl.class );
----
