== TODO ==

== MSTPrim ==

- Prim's algorithm has been reimplemented due to bugs.
- renamed to `algo.spanningTree.*`
- old proc also available
- alternative is `algo.spanningTree.minimum`
- also available is the maximumSpanningTree `algo.spanningTree.maximum`
- return values have changed
- new return value `effectiveNodeCount` (number of visited nodes)


The maximum Spanning Tree is a spanning tree consisting of only the strongest transitions.

== KSpanningTrees-Algorithm.


This algorithm has been developed as a test for clustering market-data. It calculates
either the minimum-spanning-tree or the maximum-spanning-tree and then cuts the tree at
its k-1 weakest or strongest relationships.

Note: Only write-back method exists!

The method returns computeMilis, writeMilis, loadMilis and effectiveNodeCount. The
`effectiveNodeCount` is the count of nodes seen by the prim algorithm. This might
come in handy if the startnode is part of a disconnected graph so the BFS does not reach
all nodes.

=== kMax ===

`algo.spanningTree.kmax` calculates the *MaximumSpanningTree* using Prim's Algorithm from a given
node and keeps track of the *weakest transitions* in the resulting tree. It then cuts the
tree at its `k-1` weakest relationships and assigns a partition Id to each resulting branch.

Example:

`CALL algo.spanningTree.kmax("Node", "REL", "costs", 0L, 3, {writeProperty:'partition'}`


=== kMin ===

`algo.spanningTree.kmin` calculates the *MinimumSpanningTree* using Prim's Algorithm from a given
node and keeps track of the *strongest transitions* in the resulting tree. It then cuts the
tree at its `k-1` strongest relationships and assigns a partition Id to each resulting branch.



