= Algorithms

Graph algorithms are used to compute metrics for graphs, nodes or relationships.

They can provide insights on relevant entities (centralities, ranking) in the graph or inherent structures like communities (community-detection, graph-partitioning, clustering).

Many of them are iterative aproaches that frequently traverse the graph for the computation using random walks, breadth-first- or depth-first searches or pattern matching.

Due to the exponential growth of possible paths with increasing distance many of the approaches are also of a high algorithmic complexity.

Fortunately some optimized algorithms exist that utilize certain structures of the graph, memoize of already explored parts and if possible parallelize operations.
Whenever possible we tried to apply these optimizations.

// todo introduction to graph algorithms, also say something about pregel & parallelization
// todo sensible ordering

include::triangleCount.adoc[leveloffset=2]

include::pagerank.adoc[leveloffset=2]

include::betweenness-centrality.adoc[leveloffset=2]

include::closeness-centrality.adoc[leveloffset=2]

include::minimum-weight-spanning-tree.adoc[leveloffset=2]

include::single-shortest-path.adoc[leveloffset=2]


include::label-propagation.adoc[leveloffset=2]

include::louvain.adoc[leveloffset=2]

include::connected-components.adoc[leveloffset=2]

include::strongly-connected-components.adoc[leveloffset=2]
