= Implementers Documentation

== Development Notes

NOTE: When implementing a procedure that yields any results (is not `void`) and writes back to the database, make sure to consume the `Result` after running the algo call!

Algorithms are executed within a transaction, that is opened and closed by cypher. The transaction is only marked successful if the results are consumed.
Closing the Result directly will fail and rollback any open transactions and thus will revert all write-back operations.
// StandardInternalExecutionResult#successful is only set to true _after_ the result has been consumed


== The Model

The basic idea behind our model is to have a fast cache for the
topology of the graph containing only relevant nodes, relations
and in addition the weights. It implicitly maps (long) node-id's to
a temporary integer-id in ascending order which ensures that no id gets bigger
then the maximum node count. This approach allows us to use primitive
arrays as container for example.

=== Graph Interface

[horizontal]
int vertexCount()::


    Return the count of vertices in the graph


void forEachNode(IntConsumer)::

    Calls consumer for each vertex id


PrimitiveIntIterator vertexIterator()::

    Returns an vertex id Iterator


int degree(int, Direction)::

    Return the degree for the given vertex / direction

void forEachEdge(int, Direction, EdgeConsumer) & ::

Iterator<EdgeCursor> edgeIterator(int, Direction)::

    Iterates over each edge of the given vertex / direction

void forEachEdge(int, Direction, WeightedEdgeConsumer) & ::

Iterator<WeightedEdgeCursor> weightedEdgeIterator(int, Direction)::

    Iterates over each edge of the given vertex / direction.

int toNodeId(long)::

     Map node id to vertex id

long toNodeId(int)::

      Map vertex id back to it's original node id

The interface specifies Methods for iterating over all vertices of the
graph as well as iterating over edges of a given vertex in the form of *forEach(..)*-
and *relationshipIterator()*-Methods. The Graph knows the *nodeCount* and *degree* of each node and can *map*
nodeId to vertexId and vice versa. An Iterator is implemented for (single-)weighted and unweighted edges.


[ditaa]
----

                                  +--------------+
                                  |    Graph     |
                                  +--------------+
                                  | - degree( )  |
                                  | - forEach( ) |
                                  | - relation( )|
                                  | - idMap( )   |
                                  +--------------+
                                    ^    ^     ^
                        implements  |    |     | implements
                      +-------------+    |     +----------+
                      |                  |                |
                      |                  |implements      |
                 +----+-------+    +-----+------+     +---+-------+
                 | HeavyGraph |    | LightGraph |     | GraphView |
                 +------------+    +------------+     +-----------+

----

[NOTE]
Currently we have 3 different implementations aiming for different goals like performance, memory
consumption and accuracy.

HeavyGraph::

This implementations utilizes an int-matrix for storing connections between vertices.
It has a high memory consumption but performs basic calculations on the graph
around 3 times faster then the memory efficient implementation. Furthermore the
number of edges per node is limited only to the maximum array size of the VM and
connections can be added in arbitrary order.

LightGraph::

This implementation takes 3 times less heap due to a more intelligent
memory layout. The drawback is the higher evaluation time.

View::
The View is just a single threaded Wrapper around the Neo4j core api. It has been
implemented for tests and benchmarks.

== Import

A fair amount of the work is to fetch the relevant targetNodes from the neo4j core db
and import it into our model. Fortunately we can use a multithreading approach to fill
the Graph. This is part of current development.

The abstract GraphFactory specifies a Constructor and the build Method. It is responsible
for creating the Graph using the core db.

[ditaa]
----

             +------------------+         builds        +--------------+
             |   GraphFactory   | - - - - - - - - - - > |    Graph     |
             +------+---+-------+                       +---+-----+----+
                    ^   ^                                   ^     ^
                    |   |                                   |     |
                    |   |                                   |     |
                    |   |                                   |     |
                +---+   +--------+                   +------+     +--+
                |                |                   |               |
        +-------+------+  +------+-------+    +------+-----+  +------+-----+
        | HeavyFactory |  | LightFactory |    | HeavyGraph |  | LightGraph |
        +--------------+  +--------------+    +------------+  +------------+

----

Loading the Graph is done by using the GraphLoader which implements a simple fluent Builder Pattern.

----
final Graph graph = new GraphLoader( graphDatabaseAPI )
        .setLabel( .. )
        .setRelation( .. )
        .setProperty( .. )
        .setThreadPool( .. )
        .load( FactoryImpl.class );
----

