= All Pairs- and Single Source - Shortest Path

A _Single Source Shortest Path_ algorithms calculates a path between a pair of nodes whose summed weights are minimal. A common algorithm used is Dijkstra. 

_All Pairs Shortest Path_ on the other hand calculates a shortest path forest containing all paths between the nodes in the graph. An algorithm to solve this is Floyd Warshall or Parallel Johnson's algorithm. 

== History, Explanation

Path finding, in particular searching in a maze, belongs to the classical graph problems, and the classical references are Wiener [1873], Lucas [1882] (describing a method due to C.P. Tr´emaux), and Tarry [1895] – see Biggs, Lloyd, and Wilson [1976]. 
They form the basis for depth-first search techniques.
Path problems were also studied at the beginning of the 1950’s in the context of ‘alternate routing’, that is, finding a second shortest route if the shortest route is blocked. 
This applies to freeway usage (Trueblood [1952]), but also to telephone call routing. 
At that time making long-distance calls in the U.S.A. was automatized, and alternate routes for telephone calls over the U.S. telephone network nation-wide should be found automatically.

== When to use it / use-cases

== Constraints / when not to use it

== Algorithm explanation on simple sample graph

[source,cypher]
----
MATCH (start:Node{type:'start'}), (end:Node{type:'end'})
CALL algo.shortestPath.stream(start, end, 'cost') 
YIELD nodeId, cost
                       
----


[source,cypher]
----
MATCH (start:Node{type:'start'}), (end:Node{type:'end'})
CALL algo.shortestPath(start, end, 'cost') 
YIELD loadDuration, evalDuration, nodeCount, totalCost

----

[source,cypher]
----
MATCH(n:Node {name:'s'}) WITH n CALL algo.deltaStepping.stream(n, 'cost', 3.0)
YIELD nodeId, distance RETURN nodeId, distance

----

[source,cypher]
----

MATCH(n:Node {name:'s'}) WITH n CALL algo.deltaStepping(n, 'cost', 3.0, {write:true, writeProperty:'sp'})
YIELD nodeCount, loadDuration, evalDuration, writeDuration RETURN nodeCount, loadDuration, evalDuration, writeDuration

----

== Example Usage

== References

* http://www.math.uiuc.edu/documenta/vol-ismp/32_schrijver-alexander-sp.pdf

ifdef::implementation[]
// tag::implementation[]

== Implementation Details

:leveloffset: +1
// copied from: https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/80

A _Single Source Shortest Path_ algorithms calculates a path between a pair of nodes whose summed weights are minimal. A common algorithm used is Dijkstra. _All Pairs Shortest Path_ on the other hand calculates a shortest path forest containing all paths between the nodes in the graph. An algorithm to solve this is Floyd Warshall or Parallel Johnson's algorithm. 

## Progress

- [x] single threaded implementation
- [x] tests
- [x] simple benchmark 
- [x] implement procedure
- [ ] benchmark on bigger graphs
- [ ] parallelization
- [ ] evaluation

## Requirements

`(Outgoing)RelationshipIterator` & `Weights`

## Data structured involved

- An int-based Fibonacci Heap which implements an efficient priority queue. 
- Different Container for Costs / visited state / paths

## ToDo

### benchmark

Implement benchmark on big graph

### parallelization

Parallizing _All Pairs Shortest Path_ might be easy using Dijkstra on each thread for a different node. An easy approach for _Single Source SP_ may use two threads. One starting at the start-node, one at the end-node. The first wins. [More](https://www.cs.rice.edu/~vs3/comp422/lecture-notes/comp422-lec24-s08-v2.pdf)

### evaluation

- Performance tests on different dataset sizes / level of concurrency


== Details


=== algo.shortestPath

- Dijkstra single source shortest path algorithm
- The algorithm computes a shortest path on weighted graphs
 between a given start and target-NodeId. It returns result tuples of [nodeId, distance] of each node
 in the path
- there may be more then one shortest path, algo returns only one
- if initialized with an not-existing weight-property and a defaultWeight of 1.0 the resulting path is minimal in
 terms of count of nodes in the path.

=== algo.shortestPath.deltaStepping

TODO naming!?
- parallel non-negative single source shortest path algorithm for weighted graphs
- It can be tweaked using the delta-parameter which controls the grade of concurrency.
- returns minimum distance to *all other nodes*
- if initialized with an non-existing weight-property and a defaultWeight of 1.0 its result can be interpreted as
 the number of nodes to reach the target

=== algo.allShortestPaths.stream

- returns a stream of source-target node to distance tuples for each pair of nodes
- Since all nodeId's have already been ordered by the idMapping we can use an integer
 instead of a queue which just count's up for each startNodeId as long as it is
 < nodeCount.
- Each thread tries to take one int from the counter at one time and starts its computation on it.
- The {@link AllShortestPaths#concurrency} value determines the count of workers that should be spawned.
- Due to the high memory footprint the result set would have we emit each result into
 a blocking queue. The result stream takes elements from the queue while the workers
 add elements to it.
- The result stream is limited by N^2. If the stream gets closed prematurely the workers get closed too.
- writeback not supported!

// end::implementation[]
endif::implementation[]
